import { IPersistable } from "src/app/classes/infrastructure/IPersistable";
import { DataContainer } from "src/app/classes/infrastructure/datacontainer";
import { DataContainerService } from "src/app/classes/infrastructure/datacontainer.service";
import { PayloadPacketFacade } from "src/app/classes/infrastructure/payloadpacket/payloadpacketfacade";
import { TransportData } from "src/app/classes/infrastructure/transportdata";
import { ValidationResultAccumulator } from "src/app/classes/infrastructure/validationresultaccumulator";
import { IdProvider } from "src/app/services/idprovider.service";
import { ServerCommunicatorService } from "src/app/services/server-communicator.service";
import { Utils } from "src/app/services/utils.service";
import { isNullOrUndefined } from "src/tools";
import { UIUtils } from "src/app/services/uiutils.service";
import { RequestTypes } from "src/app/classes/infrastructure/enums";
import { ValidationMessages, ValidationPatterns } from "src/app/classes/domain/constants";
import { InvoiceFetchRequest } from "./invoicefetchrequest";
import { GetDistinctRecipientNameFetchRequest } from "./GetDistinctRecipientNameFetchRequest";
import { TimeDetailProps } from "../../site_management/time/time";
import { LabourTimeProps } from "../../site_management/labourtime/labourtime";
import { ExpenseTypes } from "src/app/classes/domain/domainenums/domainenums";


export class InvoiceProps {
  public readonly Db_Table_Name = "Invoice";
  public CreatedBy: number = 0;
  public CreatedByName: string = '';
  public CreatedDate: string = ''
  public UpdatedBy: number = 0;
  public UpdatedByName: number = 0;
  public UpdatedDate: string = ''
  public Ref: number = 0;
  public CompanyRef: number = 0
  public CompanyName: string = ''

  public Date: string = ''
  public InvoiceNo: number = 0
  public SiteRef: number = 0
  public readonly SiteName: string = ''
  public LedgerRef: number = 0
  public readonly LedgerName: string = ''
  public SubLedgerRef: number = 0
  public readonly SubLedgerName: string = ''
  public ExpenseType: number = 0
  public VendorRef: number = 0
  public readonly VendorName: string = ''
  public VendorServiceRef: number = 0
  public readonly VendorServiceName: string = ''
  public VehicleNo: string = ''
  public Description: string = ''
  public RecipientType: number = 0
  public RecipientMasterRef: number = 0
  public RecipientName: string = ''
  public IsSiteRef: number = 0
  public Reason: string = ''
  public IsDieselPaid: number = 0
  public DieselQty: number = 0
  public DieselRate: number = 0
  public DieselAmount: number = 0
  public Qty: number = 0
  public UnitRef: number = 0
  public readonly UnitName: string = ''
  public Rate: number = 0
  public InvoiceAmount: number = 0
  public InvoiceModeOfPayment: number = 0
  public Narration: string = ''
  public TransDateTime: string = ''
  public IsDeleted: number = 0
  public MachineUsageDetailsArray: TimeDetailProps[] = [];
  public LabourExpenseDetailsArray: LabourTimeProps[] = [];
  public readonly AddressLine1: string = ''
  public readonly AddressLine2: string = ''
  public readonly CityName: string = ''
  public readonly Contacts: string = ''
  public readonly OwnerName: string = ''
  public BankAccountRef: number = 0
  public IsInvoiceAutoGenerated: number = 0

  OtherExpenseRef: number = ExpenseTypes.OtherExpense


  public readonly IsNewlyCreated: boolean = false;
  // public readonly AccountTypeName: string = '';

  private constructor(isNewlyCreated: boolean) {
    this.IsNewlyCreated = isNewlyCreated;
  }

  public static Blank() {
    return new InvoiceProps(true);
  }
}

export class Invoice implements IPersistable<Invoice> {
  public static readonly Db_Table_Name: string = 'Invoice';

  private constructor(public readonly p: InvoiceProps, public readonly AllowEdit: boolean) {

  }

  public async EnsurePrimaryKeysWithValidValues(): Promise<void> {
    if (this.p.Ref === undefined || this.p.Ref === 0) {
      const newRefs = await IdProvider.GetInstance().GetNextEntityId();
      // const newRefs = await IdProvider.GetInstance().GetAllocateSingleIds();
      this.p.Ref = newRefs[0];
      if (this.p.Ref <= 0) throw new Error("Cannot assign Id. Please try again");
    }
  }

  public GetEditableVersion(): Invoice {
    let newState: InvoiceProps = Utils.GetInstance().DeepCopy(this.p);
    return Invoice.CreateInstance(newState, true);
  }

  public static CreateNewInstance() {
    return new Invoice(InvoiceProps.Blank(), true);
  }

  public static CreateInstance(data: any, allowEdit: boolean) {
    return new Invoice(data as InvoiceProps, allowEdit);
  }

  public CheckSaveValidity(_td: TransportData, vra: ValidationResultAccumulator): void {
    if (!this.AllowEdit) vra.add('', 'This object is not editable and hence cannot be saved.');
    if (this.p.Date == '') { vra.add('Date', 'Date cannot be blank.'); }
    if (this.p.SiteRef <= 0) { vra.add('SiteRef', 'Site Name cannot be blank.'); }
    if (this.p.LedgerRef <= 0) { vra.add('LedgerRef', 'Ledger cannot be blank.'); }
    if (this.p.ExpenseType <= 0) { vra.add('ExpenseType', 'Expense Type cannot be blank.'); }
    // if (this.p.Description == '') { vra.add('Description', 'Description cannot be blank.'); }
    if (this.p.Qty <= 0 && this.p.ExpenseType == this.p.OtherExpenseRef) { vra.add('Qty', 'Quantity cannot be blank.'); }
    // if (this.p.Rate <= 0) { vra.add('Rate', 'Rate cannot be blank.'); }
    if (this.p.IsDieselPaid == 1) {
      if (this.p.DieselQty <= 0) { vra.add('DieselQty', ' Diesel Quantity cannot be blank.'); }
      if (this.p.DieselRate <= 0) { vra.add('DieselRate', ' Diesel Rate cannot be blank.'); }
    }
  }

  public MergeIntoTransportData(td: TransportData) {
    DataContainerService.GetInstance().MergeIntoContainer(td.MainData, Invoice.Db_Table_Name, this.p);
  }

  private static m_currentInstance: Invoice = Invoice.CreateNewInstance();

  public static GetCurrentInstance() {
    return Invoice.m_currentInstance;
  }

  public static SetCurrentInstance(value: Invoice) {
    Invoice.m_currentInstance = value;
  }


  // ********************************************
  public static cacheDataChangeLevel: number = -1;

  public static SingleInstanceFromTransportData(td: TransportData): Invoice {
    let dcs = DataContainerService.GetInstance();
    if (dcs.CollectionExists(td.MainData, Invoice.Db_Table_Name)) {
      for (let data of dcs.GetCollection(td.MainData, Invoice.Db_Table_Name)!.Entries) {
        return Invoice.CreateInstance(data, false);
      }
    }

    return null as any;
  }

  public static ListFromDataContainer(cont: DataContainer,
    filterPredicate: (arg0: any) => boolean = null as any,
    //sortPropertyName: string = "Name"): Invoice[] {
    sortPropertyName: string = ""): Invoice[] {
    let result: Invoice[] = [];

    let dcs = DataContainerService.GetInstance();

    if (dcs.CollectionExists(cont, Invoice.Db_Table_Name)) {
      let coll = dcs.GetCollection(cont, Invoice.Db_Table_Name)!;
      let entries = coll.Entries;

      if (!isNullOrUndefined(filterPredicate)) entries = entries.filter(filterPredicate);

      if (sortPropertyName.trim().length > 0) {
        entries = Utils.OrderByPropertyName(entries, sortPropertyName);
      }

      for (let data of entries) {
        result.push(Invoice.CreateInstance(data, false));
      }
    }

    return result;
  }

  public static ListFromTransportData(td: TransportData): Invoice[] {
    return Invoice.ListFromDataContainer(td.MainData);
  }

  public static async FetchTransportData(req: InvoiceFetchRequest, errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
    let tdRequest = req.FormulateTransportData();
    let pktRequest = PayloadPacketFacade.GetInstance().CreateNewPayloadPacket2(tdRequest);

    let tr = await ServerCommunicatorService.GetInstance().sendHttpRequest(pktRequest);
    if (!tr.Successful) {
      if (!isNullOrUndefined(errorHandler)) await errorHandler(tr.Message);
      return null;
    }

    let tdResponse = JSON.parse(tr.Tag) as TransportData;
    return tdResponse;
  }

  public static async FetchInstance(ref: number, errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
    let req = new InvoiceFetchRequest();
    req.InvoiceRefs.push(ref);

    let tdResponse = await Invoice.FetchTransportData(req, errorHandler) as TransportData;
    return Invoice.SingleInstanceFromTransportData(tdResponse);
  }

  public static async FetchList(req: InvoiceFetchRequest, errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
    let tdResponse = await Invoice.FetchTransportData(req, errorHandler) as TransportData;
    return Invoice.ListFromTransportData(tdResponse);
  }

  public static async FetchEntireList(errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
    let req = new InvoiceFetchRequest();
    let tdResponse = await Invoice.FetchTransportData(req, errorHandler) as TransportData;
    return Invoice.ListFromTransportData(tdResponse);
  }

  public static async FetchEntireListByCompanyRef(CompanyRef: number, errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
    let req = new InvoiceFetchRequest();
    req.CompanyRefs.push(CompanyRef)
    let tdResponse = await Invoice.FetchTransportData(req, errorHandler) as TransportData;
    return Invoice.ListFromTransportData(tdResponse);
  }

  public static async FetchRecipientByRecipientTypeRef(CompanyRef: number, RecipientType: number, errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
    let req = new GetDistinctRecipientNameFetchRequest();
    req.CompanyRef = CompanyRef
    req.RecipientType = RecipientType
    let tdResponse = await Invoice.FetchTransportData(req, errorHandler) as TransportData;
    return Invoice.ListFromTransportData(tdResponse);
  }

     public static async FetchEntireListByFilters(SiteRef:number, LedgerRef:number,SubLedgerRef:number,Ref:number, CompanyRef: number, errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
      let req = new InvoiceFetchRequest();
      req.CompanyRefs.push(CompanyRef)
      if (LedgerRef) {
        req.LedgerRefs.push(LedgerRef)
      }
      if (SubLedgerRef) {
         req.SubLedgerRefs.push(SubLedgerRef)
      }
      if (SiteRef) {
         req.SiteRefs.push(SiteRef)
      }
      if (Ref) {
         req.Refs.push(Ref)
      }
      let tdResponse = await Invoice.FetchTransportData(req, errorHandler) as TransportData;
      return Invoice.ListFromTransportData(tdResponse);
    }

  public async DeleteInstance(successHandler: () => Promise<void> = null!, errorHandler: (err: string) => Promise<void> = UIUtils.GetInstance().GlobalUIErrorHandler) {
    let tdRequest = new TransportData();
    tdRequest.RequestType = RequestTypes.Deletion;

    this.MergeIntoTransportData(tdRequest);
    let pktRequest = PayloadPacketFacade.GetInstance().CreateNewPayloadPacket2(tdRequest);

    let tr = await ServerCommunicatorService.GetInstance().sendHttpRequest(pktRequest);
    if (!tr.Successful) {
      if (!isNullOrUndefined(errorHandler)) await errorHandler(tr.Message);
    }
    else {
      if (!isNullOrUndefined(successHandler)) await successHandler();
    }
  }

}
